### ISSUE TITLE
Smart cut does not recognize new industries in Pine Valley

### ISSUE THREAD

**Issue by scottanderson** [scottanderson/railroad.studio#104]
The new industry types, such as `CattleFarm`, `MeatPackingPlant`, `Sandhouse`, and `watertower_drgw` are not recognized by smart cut.

**Comment by nothenrycat** [comment]
What is "smart cut"? I have one older Lake Valley layout where it recognizes the cattle farm and allowed me to edit its contents, but now, with a more recent layout, it doesn't work anymore. Hence my question: What is "smart cut"?

**Comment by scottanderson** [comment]
Smart cut is a Pine Valley only tool, as Lake Valley's trees to not work in the same way. Smart cut is used for cutting trees that are too close to industries or tracks.

**Comment by jaltadonna** [comment]
Oh okay

**Comment by jaltadonna** [comment]
But why can't you in pine vally cut all trees then use smart plant trees, thats what not working is when you cut all trees the smart plant plant trees does not work. becAUSE being able to see the inclines and and stuff helps lay the track plus you don't have to cut the trees.

then when your done with the track laying you can use smart plant trees to put them all bacvk or is that not how it works

**Comment by illudedPerception** [comment]
not that smart cut does not work the cut all and plat all also is not working and seems they moved the tree grid a bit so that affects the alltrees.dat ? is the alltrees.dat just a copy of the tree data from the save file and just saved as .dat so the info would not dissepear ?

**Comment by illudedPerception** [comment]
so the cut all and plant all trees will work until the save file is saved by the game and then the size goes from 5mb (trees cut and save downloaded from studio) to 10mb, same save file just overwritten by the game with cut all trees done to it

**Comment by illudedPerception** [comment]
i see the problem now, they save the cut trees in `vegetation` not `removedVegetationAssets` and its a bit over my head to change that i get bunch of errors

**Comment by scottanderson** [comment]
This issue is for adding the new industries to Pine Valley tree tools. These tools operate on the `removedVegitationAssets` property which is only used with the Pine Valley map.

Support for Lake Valley, which uses the `removedVegetationAssets` property, is discussed in #41.

[edit] Railroads Online now uses the `vegetation` property for all maps, but it still supports loading Lake Valley maps with the legacy `removedVegetationAssets` property as long as the `vegetation` property is not also set. To prevent RO from crashing,  the legacy tree tools are now disabled whenever `vegetation` is detected (#119). To access the legacy tree tools on a Pine Valley save, first use the new vegetation tool to plant all vegetation, export and load the modified save file in to Railroad Studio.

**Comment by scottanderson** [comment]
Resolved with #118 / #120
