### ISSUE TITLE
Failed to load: Error: Unexpected flags 0 for component type 0

### ISSUE THREAD

**Issue by RamuhVII** [scottanderson/railroad.studio#123]
**Attach the save file**
The game file is not supported here. I cannot attach it.

**Describe the bug**
I dragged the saved game file to copy just like normal. But something happened to my file. Rail road studio responds with:
Error: Unexpected flags 0 for component type 0
    at https://railroad.studio/studio.js:1:257836
    at Xi (https://railroad.studio/studio.js:1:258752)
    at Yi (https://railroad.studio/studio.js:1:251107)
    at https://railroad.studio/studio.js:1:261268
    at https://railroad.studio/studio.js:1:261471
    at https://railroad.studio/studio.js:1:260048
The file used to work until I added or moved something in game.

Other save files are fine.
If I could get an answer and find the issue in the game,
PS Measurement and duplication don't work.

**Comment by scottanderson** [comment]
As mentioned in the first line of the issue template, you need to zip your save file before attaching it to github.

**Comment by scottanderson** [comment]
This should be fixed by #125

**Comment by RamuhVII** [comment]
Dear sir, you are genius! Thanks so much. I’m a disabled vet who loved
trains and trolleys (trams).  I fixed busses, trolleys, and military
equipment but now I had to retire due my health. My save file works today.
I don’t know what you did but thanks!
