### ISSUE TITLE
Mass Modify Frame Vectors

### ISSUE THREAD

**Issue by Erabior** [scottanderson/railroad.studio#13]
**Is your feature request related to a problem? Please describe.**
some updates to the game have caused users to retail all cars and locos. Additionally it could be useful if people modify the track in RR studio and it would be nice to translate en mass any affected cars.

**Describe the solution you'd like**
It would be useful to be able to mass modify the vectors of all frames in a save. Similar to how there are up and down arrows in the vector value boxes already but that affect the x/y/z values for all or selected cars in the save

**Describe alternatives you've considered**
The only alternative is going through manually adjusting the values

**Additional context**
Thank you!

**Comment by scottanderson** [comment]
You can achieve this functionality by running this command in the browser console (F12):
```js
window.studio.railroad.frames.forEach(f => f.location.z += 100) // increase height by 1m
```

It would require a fair bit of work to create a friendly user interface to do this, so I probably won't have time to do that any time soon. I will leave this issue open in case someone wants to create a PR for this.
