### ISSUE TITLE
style.css

### ISSUE THREAD

**Issue by illudedPerception** [scottanderson/railroad.studio#139]
did the style css got pushed to live ? cause i see the fences don't have transparent background (red circle) and the green circle should be a lighter shade of the 'building' fill or **i did something wrong ?**
![image](https://github.com/scottanderson/railroad.studio/assets/126168696/02558f35-3a75-4cc5-9848-01caa2b8f33d)
it should look like this, what is my local version running with the modified css
![image](https://github.com/scottanderson/railroad.studio/assets/126168696/d6fc0bc7-1d3f-491b-af62-9d701aa77828)

**Comment by scottanderson** [comment]
Your web browser may be caching an old version of the file. You can usually force your web browser to request a new file by holding ctrl when refreshing. Can you please try this and let me know if you're still not seeing the updated styles?

I do see the `fence` style when I load the page, but to be sure that all of the CDN instances are consistent, I verified in the [deployment log](https://github.com/scottanderson/railroad.studio/actions/runs/8011689836/job/21885455474) that style.css was uploaded to s3, and that the CloudFront invalidation path covers `/*`. Based on this, I believe that RS should be serving the correct version of the file from all CDN locations.
