### ISSUE TITLE
An unusual request for Scott Anderson

### ISSUE THREAD

**Issue by nothenrycat** [scottanderson/railroad.studio#149]
**Attach the save file**
Add the .sav file to a zip, and attach the .zip file to this issue.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nothenrycat** [comment]
Hi Scott,
I contact you this way because I can't find another way to contact you. As you surely know has Tom of Railroad Online Extended recently decided to discontinue his work on it because of the lack of support from the RRO team. Since you with RailroadStudio now seem to have just about everthing figured out, including a great map for Aurora Falls (for all of it I want to congratulate you!), I wanted to ask you, if it might be possible for you to have a look at the RROX code, which is also on Github, and see if you can see a way if you or somebody could update RROX and bring it up to scratch. I don't know whether this would be alright with Tom, but I can't really see why he would object if somebody else picks up his work. There seems to be no copyright or something!
Thanks for your excellent work!

**Comment by scottanderson** [comment]
This is not something I have interest in taking on.
