### ISSUE TITLE
Add an opacity toggle

### ISSUE THREAD

**Issue by doccy-doc** [scottanderson/railroad.studio#150]
Problem: Splines can be difficult to identify against the heightmap background.

Idea: Adding a simple toggle/slider for map opacity would allow users to increase visibility of the objects/tracks, or the heightmap image. 

Concept: I believe this can be achieved by modifying `#background` css property `opacity: xx%` to the desired value.

Standard 100% opacity (top) vs 30% opacity (bottom)
![rs-opacity-3](https://github.com/scottanderson/railroad.studio/assets/4121848/bc0e6807-c300-40a0-b202-e36ce6668494)

**Comment by scottanderson** [comment]
One issue with this approach is that lowering opacity also lowers contrast, which can make text harder to read.

I think a better approach would be to look for a CSS `filter` function to modify the color, such as `filter: sepia(80%)`.

Alternatively, you could work with @illudedPerception to generate a new mage image with colors that more closely match the color pallet of the old topo map.

**Comment by illudedPerception** [comment]
il deal with the color, tomorrow its 2am here :D i might work with the lines too a bit but il see

**Comment by doccy-doc** [comment]
My thoughts are, that if it is a toggle or slider that is user adjustable, then the user can choose whether they want legibility of the topographical map or the splines. If they want legibility of the text (read: heightmap readings), the user can increase the opacity. At 50% opacity, the text is still quite legible, so maybe that can be a targeted value?

Another solution would be to have a `<div class="imgoverlay">` with a  css `.imgoverlay { background-color: rgba(255, 255, 255, 0); }` (inverted to `rgba(0, 0, 0, 0)` for dark-mode) over the top of the background image, and manipulate the alpha channel of that layer based on the user's choice. This would have the benefit of keeping the background colour's contrast.

50% opacity map: 
![image](https://github.com/scottanderson/railroad.studio/assets/4121848/c7954e31-56f7-48c8-891f-9979e7989e61)

**Comment by scottanderson** [comment]
You can hide the topographical map from the layers menu.

**Comment by doccy-doc** [comment]
Understood, but not quite the issue. My issue specifically is that splines and topo lines, particularly stonewall splines, are difficult to distinguish from each other at a glance. Legibility of both are therefore compromised. 

My use case has me wanting to see both the topo lines and the splines, as is (what I assume to be - I could be wrong) the most common way of using the app. 

I am currently working around this legibility issue using dev tools to modify the alpha channel of the image. This is, however, not ideal, as I have to modify this css every time I reload the app, and as you suggested, it does reduce the contrast. 

It would be great to have this addressed, but if it is too trivial, then feel free to close the issue as `wont-fix` and I will continue to use my own workaround. I just thought it would be a small but good QoL addition for users.

**Comment by scottanderson** [comment]
I agree that this is a problem, but I do not think that lowering the opacity is a good solution. Instead, the images can be updated to use a different color pallet.

**Comment by illudedPerception** [comment]
well the new stuff looks like this MINUS the grid (the grid is for steam)
![image](https://github.com/scottanderson/railroad.studio/assets/126168696/69d833e3-d7d2-46c4-9c76-b7c390d7d8ee)
