### ISSUE TITLE
Add support for props / Transform data type

### ISSUE THREAD

**Issue by wolfmg** [scottanderson/railroad.studio#20]
Since last update no longer to open save woth beta branch

**Comment by scottanderson** [comment]
Please include an affected save file.

**Comment by wolfmg** [comment]
![error](https://github.com/scottanderson/railroad.studio/assets/144496519/c0e2c86e-799a-4dae-8e75-997a08dd2e12)
 
ive already tried but they said that github dont support the file , but here a screen shot of the error i receive everytime i try to open a BETA save , all my old STABLE file can be open

**Comment by wolfmg** [comment]
[WOLF MAIN BETA !!!.zip](https://github.com/scottanderson/railroad.studio/files/12564655/WOLF.MAIN.BETA.zip)

never mind here my main BETA save that railroad studio cant open

**Comment by scottanderson** [comment]
Two key modifications have been made to the data storage format in this file:

1. Transforms have been added. UE stores these in a complex data type that RS has not needed to support previously. I have begun updating the property parsing logic in PR #22, as the previous logic did not account for nested properties. More work is needed to complete support for reading and writing the Transform data structure.

2. String formats have changed subtly. This is minor but does require some special handling to ensure that exported save files are identical to the file that was read in.

I verified that [the gvas Rust library](https://github.com/localcc/gvas) can read this file after a minor adjustment to support item number two - so at this point, the data format is known and the work remaining is a matter of implementing the CustomStruct parsing code in to RS. For context, here's an example of the data in a Vector vs the new Transform type, as viewed by the gvas library. This output was created using [gvas2json](https://github.com/scottanderson/gvas2json).

Vector:
```
{
    "type": "StructProperty",
    "value": {
        "VectorD": {
            "x": 7433.134933849617,
            "y": -2232.8017708001603,
            "z": 10278.925226515496
        }
    }
}
```

Transform:
```
{
    "type": "StructProperty",
    "value": {
        "CustomStruct": [
            "Transform",
            [
                [
                    "Rotation",
                    {
                        "type": "StructProperty",
                        "value": {
                            "QuatD": {
                                "w": -0.048261160609787745,
                                "x": 0,
                                "y": 0,
                                "z": -0.9988347512860156
                            }
                        }
                    }
                ],
                [
                    "Translation",
                    {
                        "type": "StructProperty",
                        "value": {
                            "VectorD": {
                                "x": 117226.93054728398,
                                "y": 41213.63177366535,
                                "z": 10695.480555252918
                            }
                        }
                    }
                ],
                [
                    "Scale3D",
                    {
                        "type": "StructProperty",
                        "value": {
                            "VectorD": {
                                "x": 1,
                                "y": 1,
                                "z": 1
                            }
                        }
                    }
                ]
            ]
        ]
    }
}
```

**Comment by xXPinkFloyd92Xx** [comment]
@scottanderson Thank you for working on it. Looking forward to a fix.

**Comment by scottanderson** [comment]
I was able to get the file parsing logic working yesterday for all three new types (Quat, non-array Vector, and Transform array), so this is more than half way done. The next step is to get file export working for these types.
