### ISSUE TITLE
GB4 save files fail to load with a confusing error message

### ISSUE THREAD

**Issue by reyayer** [scottanderson/railroad.studio#201]
[GUNDAMBREAKER4.zip](https://github.com/user-attachments/files/16920915/GUNDAMBREAKER4.zip)

When trying to open this .sav file I get the error message Failed to load: RangeError: Invalid typed array length: 1867382784
RangeError: Invalid typed array length: 1867382784
    at new Uint8Array (<anonymous>)
    at Is (https://railroad.studio/studio.js:1:266837)
    at zs (https://railroad.studio/studio.js:1:268630)
    at Rs (https://railroad.studio/studio.js:1:267390)
    at https://railroad.studio/studio.js:1:278132
    at https://railroad.studio/studio.js:1:278335
    at https://railroad.studio/studio.js:1:276892

**Comment by scottanderson** [comment]
Railroad Studio supports save files for the game Railroads Online only. I'm going to use this issue to track that we could display a more helpful error message in this situation.

As for how you can view or edit the attached save file, one option would be to open an issue with the [gvas](https://github.com/localcc/gvas/issues) project to add support for this game. Once resolved, you could use [gvas2json](https://github.com/scottanderson/gvas2json) to convert the save file to an editable format.
