### ISSUE TITLE
Anniversary Update of RRO

### ISSUE THREAD

**Issue by nothenrycat** [scottanderson/railroad.studio#212]
**Attach the save file**
Add the .sav file to a zip, and attach the .zip file to this issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by nothenrycat** [comment]
Hi Scott,
Since the anniversary update of RRO RailroadStudio isn't working any more. Will the be an update? Thanks.

**Comment by scottanderson** [comment]
@nothenrycat this issue is incomplete, please include an affected save file.

**Comment by MachinePlaygroundPeopleMachine** [comment]
> @nothenrycat this issue is incomplete, please include an affected save file.

I'll give you mine in the hopes this is fixed soon. 
[Beta Save File.zip](https://github.com/user-attachments/files/17249248/Beta.Save.File.zip)
