### ISSUE TITLE
Anniversary Beta Still not loadable

### ISSUE THREAD

**Issue by GreenFoxProductions** [scottanderson/railroad.studio#216]
Now i have seen that this is a supposedly Closed issue, however it is not actually fixed for some reason. This is on the Beta branch of Railroads online (october 1st update) and not the Main branch.

**The save file**
[2024RailroadStudioIssue.zip](https://github.com/user-attachments/files/17259013/2024RailroadStudioIssue.zip)

**The issue**
The .sav file won't load up and throws out the message described in the screenshot.
this happens after a save is loaded and saved over in the new beta branch, even when just loading the save, saving the game and closing the game.

**Expected behavior**
For the .sav file to load up and be editable

**Screenshots**
![image](https://github.com/user-attachments/assets/3c6a3f6c-b23e-4fe1-82b3-ba2fdc5ef928)

I hope this helps

**Comment by RichardDastardly** [comment]
If it's your local copy, npm update & then rebuild it.

**Comment by scottanderson** [comment]
@GreenFoxProductions, your browser is caching an old version of RS. You can force Google Chrome to check for updates by holding ctrl while refreshing. For other web browsers, you may need to consult the browser's documentation for instructions on how to force reload a page without using cached content.

With that said, this save still does not load and will require more effort to get working.

**Comment by GreenFoxProductions** [comment]
So, i did fully refresh and clear cache etc. and while it did remove this issue it basically made a different one saying:

Failed to load: Error: Unexpected GUID: 
Error: Unexpected GUID: 
    at ri (https://railroad.studio/studio.js:1:130987)
    at https://railroad.studio/studio.js:1:226318
    at Array.flatMap (<anonymous>)
    at new Ps (https://railroad.studio/studio.js:1:226142)
    at https://railroad.studio/studio.js:1:292996
    at https://railroad.studio/studio.js:1:278848
    
Im kinda just dumbfounded at what to do at this point

**Comment by scottanderson** [comment]
@GreenFoxProductions please try it again now - I have pushed a fix for the GUID error. Please note that #217 is still in progress.
