### ISSUE TITLE
Anniversary update  issue: many missing vehicles

### ISSUE THREAD

**Issue by RichardDastardly** [scottanderson/railroad.studio#217]
https://drive.google.com/file/d/1iHcbFLSSRgaKs8iB3J3w2W2nfyezIcLB/view?usp=drive_link

There should be 319 vehicles in this save - I haven't worked out precisely what's missing, but it's about 100 of them! at least the D&RG gondolas, big stake flats ( I think they show as Flatcar Tier 2? ), oil tankers are all missing.

If I load a save exported from the previous game version all frames are present ( eg, this one - https://drive.google.com/file/d/1RC4zElCgC1gXkc1kyU7aBA9WN8dKU5_r/view?usp=drive_link )

**Comment by scottanderson** [comment]
@RichardDastardly please follow the directions in the bug template to attach your save file to this issue. I do not have access to the link provided.

**Comment by RichardDastardly** [comment]
Mea culpa - the files were already there & *should* be accessible anyway ( so claims google ).

Save from current beta - 
[PV 2.023 new beta.sav.zip](https://github.com/user-attachments/files/17262597/PV.2.023.new.beta.sav.zip)

Save from previous game which still loads all frames -
[PV 2.021.sav.zip](https://github.com/user-attachments/files/17262601/PV.2.021.sav.zip)

From the console log I guess they just renamed a lot of vehicles, so frame entries are going to need aliasing.

**Comment by scottanderson** [comment]
Thank you for the report. It appears that the capitalization of several industries and rolling stock have been changed in the save files.
