### ISSUE TITLE
RO build 51269: RRS is not fully populating the dropdown list of frame types.

### ISSUE THREAD

**Issue by RichardDastardly** [scottanderson/railroad.studio#222]
Slightly odd one: in saves of current build ( 51269 ) 

* The complete list of frames is apparently listing every vehicle in the save.
* Every type appears to be showing up on the map.
* However the dropdown list does not have - at least - "D&RGW 33FT Gondola" as a selectable type. I'm not sure if anything else is missing right now.

A D&RGW gondola is the last entry in the frames table in this save. I can't see anything about it in the console ( all I can see is "Unrecognized industry type TelegraphOffice_Foundation" which is another issue! ).

[PV 2.026.sav.zip](https://github.com/user-attachments/files/17397734/PV.2.026.sav.zip)

**Comment by scottanderson** [comment]
I'm not able to reproduce the issue. The 33ft gondola does appear in the dropdown for me:
![image](https://github.com/user-attachments/assets/07e94674-f1f9-472f-b8ca-0a308bbd5682)

**Comment by RichardDastardly** [comment]
Hi Scott, it's the dropdown list of *types* you get with the upper row Frames button ( I'd actually forgotten about the list you used or I'd have put a screenshot in to make it clear )

![rrs1](https://github.com/user-attachments/assets/f410a8fd-7cdb-434a-9a42-dd80495fe282)

**Comment by scottanderson** [comment]
Thanks for the report @RichardDastardly. It appears to be a bug in the filtering code where it doesn't take in to account aliased frame types properly. I'll post a fix shortly.
