### ISSUE TITLE
Spline ID map overlay

### ISSUE THREAD

**Issue by RichardDastardly** [scottanderson/railroad.studio#227]
Something I've just noticed I'm missing after trying to do some tricky work with splines, is a quick method of IDing a spline section on the map - currently I've been relying on either otherwise unused paint ( for bridges ) or using a track type I don't use anywhere else temporarily so I can find the section in the list, but it'd be far easier if I could just get the number from a map overlay.

**Comment by scottanderson** [comment]
When you click on a spline without an active tool selected, the spline's index is logged to the browser's console log.

![image](https://github.com/user-attachments/assets/b0502807-f00f-4672-8de2-b0f549981fbd)
