### ISSUE TITLE
Frame Numbers

### ISSUE THREAD

**Issue by GreenFoxProductions** [scottanderson/railroad.studio#228]
Just a simple site suggestion. Just like how numbers in "vectors" and "rotation" have arrows to up or down the value, so maybe take those and do the same to the "number" value on the frame where it takes the current number and adds 1 or removes 1 depending on the arrow thats clicked.

If this doesn't make sense then i can admit im tired as hell at the moment.

**Comment by scottanderson** [comment]
Thanks for the suggestion. The number field actually stores text, so using the numeric type would prevent inputting non-numeric text.
