### ISSUE TITLE
[serialization] Unexpected component type 4 error

### ISSUE THREAD

**Issue by RichardDastardly** [scottanderson/railroad.studio#239]
For validation, attached is a build 51996 save with all new rollingstock ( inc. paid DLC ) & the new depot ( counts as an industry ) - I have not laid any new props. There is currently a bug with liveries missing in the game, so I don't think the game's counts are necessarily accurate.

Thanks for all your work!

[PV 2.056.sav.zip](https://github.com/user-attachments/files/18031023/PV.2.056.sav.zip)

**Comment by Griffon26Griffik** [comment]
Hi, I have a problem opening saves with new version of the game too. Just writing for info to let author know... No new content bought, just lvl 10 progress and unable to load. Still getting message:  Failed to load: Error: Unexpected component type 4 with flags 1
Error: Unexpected component type 4 with flags 1
    at https://railroad.studio/studio.js:1:279272
    at Ba (https://railroad.studio/studio.js:1:280193)
    at Oa (https://railroad.studio/studio.js:1:271987)
    at https://railroad.studio/studio.js:1:282772
    at https://railroad.studio/studio.js:1:282975
    at https://railroad.studio/studio.js:1:281516
Thank you for your effort to update the mod. Its golden if working. Have a nice day

**Comment by illudedPerception** [comment]
I would work patching stuff in my self so studio would work but, im really busy with personal stuff, also a new map image also is 100% out of the question because i don't have the tools to pull cords out of the game to generate the topo maps you guys have gotten used to since i added them

**Comment by scottanderson** [comment]
On first look, I see at least two issues with the new files:
1. FTextHistory::AsNumber ("component type 4") is not supported by RS. This is relatively straightforward to add.
2. As @illudedPerception discovered (see https://github.com/scottanderson/gvas2json/issues/62), there is a GVAS file format change that requires more research to properly de-serialize.

**Comment by scottanderson** [comment]
Let's use this issue for the `Unexpected component type 4` deserialization error folks are seeing, and the corresponding serialization issue that would occur when exporting.

Please feel free to open additional issues for other feature areas, ie:
1. [serialization] This issue, for being able to load/save the files with RS.
2. [frames] An issue for adding all of the new rolling stock metadata.
3. [maps] An issue for the new map.
4. [other] Etc.
