### ISSUE TITLE
Downloading edited save file

### ISSUE THREAD

**Issue by Wargamz** [scottanderson/railroad.studio#24]
Edited save file does not download. Export button turns yellow, all changes are saved, and clicking the export button does nothing. Changing browsers does nothing. Railroad Studio worked on a previous save in an older version of the game, and I saw ROSE was updated with this newest update. Any idea what would be going on?

**Comment by Disnydude1** [comment]
Yes. I have noticed the same thing today (9/16/23).
Worked earlier this week. I was able to cut/replant trees and upload the modified saves. 
Today No.

**Comment by scottanderson** [comment]
I cannot reproduce this issue. Please attach an affected save file.

**Comment by Wargamz** [comment]
I'm unable to attach it to here, .SAV files are not supported. Compressing it to a zip file doesn't work either, though I'm not knowledgeable in files and coding at all.

**Comment by Disnydude1** [comment]
I am not even able to copy and paste a sav file from the RRO appdata saved games folder into this box. Says not supported format. How in the heck are we supposed to upload a problem if it isnt being recognized.??
After the yellow arrow appears. It will not upload the modified file to load into Railroads Online.
We also now cannot moved industries or tweak our rolling stock. 
Hopefully you can find out why this is happening. Like I said it did work right after the Beta update last week. But then when i tried this weekend Fri And yesterday. Not able to.

**Comment by Wargamz** [comment]
I actually figured it out. If you participate in the beta version of the game on Steam, it works just fine on Google Chrome. Not sure why the base game won't work.
