### ISSUE TITLE
Files Won't download

### ISSUE THREAD

**Issue by Trainz2221** [scottanderson/railroad.studio#29]
File won't download when i press button

1. literally just use the thing

expected the thing to download

**Comment by scottanderson** [comment]
Could you please share an affected save file?

**Comment by nothenrycat** [comment]
RRO have introduced a new map. With the old map - "Pine Valley" - Railroad Studio works fine, even with the new placable industries, but with the new map - "Lake Valley" - the prg does not work any more. Therefore, it seems to me, you need to get a topo map of the Lake Valley map..

**Comment by Trainz2221** [comment]
I'm using lake valley, so that's why
