### ISSUE TITLE
cant find my rolling stock on the frames category

### ISSUE THREAD

**Issue by edwardo25** [scottanderson/railroad.studio#4]
when i click on the frames category to change the names and numbers of my rolling stock, i get 4 of my tier 1 cars and 2 of my tier 2 cars, but at the top it shows that i have 28 cars. im confused why only a select few are showing up while the rest are not listed at all.

![Screenshot (1642)](https://user-images.githubusercontent.com/127633549/224514825-9ec481e1-61a2-489c-a24e-c4b0c5e72041.png)
![Screenshot (1643)](https://user-images.githubusercontent.com/127633549/224514827-25536dff-77a3-4045-9ec2-b087cea1fac4.png)
![Screenshot (1644)](https://user-images.githubusercontent.com/127633549/224514828-4ac7efa2-b147-476c-bbac-beb2dd2bc216.png)

**Comment by scottanderson** [comment]
Fixed in 89ec9b9027cff813f10faefc8131d8467650ffa3
