### ISSUE TITLE
Still can't download saves on lake valley

### ISSUE THREAD

**Issue by Trainz2221** [scottanderson/railroad.studio#42]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by scottanderson** [comment]
I am not able to reproduce this issue. If you would share your save file, that might help me to reproduce the problem. You may need to zip your save file to attach it to the github issue.

**Comment by Trainz2221** [comment]
[New WinRAR ZIP archive.zip](https://github.com/scottanderson/railroad.studio/files/12908395/New.WinRAR.ZIP.archive.zip)
