### ISSUE TITLE
Errors loading November update save files

### ISSUE THREAD

**Issue by nothenrycat** [scottanderson/railroad.studio#63]
**Describe the bug**

Oi@https://railroad.studio/studio.js:1:246938
Bi@https://railroad.studio/studio.js:1:239413
ji/</</l<@https://railroad.studio/studio.js:1:249179
ji/</<@https://railroad.studio/studio.js:1:249382
ji/a/<@https://railroad.studio/studio.js:1:248000

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RichardDastardly** [comment]
Here's an example savegame in the new format - https://www.dropbox.com/scl/fi/ek6ep5oaa4dr0amwkunnp/1.26-right-then-Mr-Bridger.sav.zip?rlkey=sk96tqeebbpqkwgfdghwy7gml&dl=0

19/11 - linked new save file post-hotfix that renamed passenger coaches.

**Comment by scottanderson** [comment]
Thank you @nothenrycat for the report, and thank you for sharing your save file @RichardDastardly. There are some fairly significant changes to the save data structure in this update.

I have updated the parser and exporter to support reading and writing the new `EnumProperty`, `NameProperty`, and `DateTime` types, and I have created [milestone 1] to track the work remaining to support the new `IndustryNameArray`, `FreightTypes`, `TurntableTypes`, and `SplineTrackIds` properties. At this time you can expect to see a `values are missing` error related to the new properties when loading a save file in the new format. 

![image](https://github.com/scottanderson/railroad.studio/assets/662325/a24602bf-906e-4cd6-a771-104d4287b599)

[milestone 1]: https://github.com/scottanderson/railroad.studio/milestone/1

**Comment by Bullzdozer** [comment]
Failed to load: Error: Some frame values are missing

ds/</</</e<@https://railroad.studio/studio.js:1:259612
ds/</</<@https://railroad.studio/studio.js:1:266720
ds/a/<@https://railroad.studio/studio.js:1:255478

trying to load a save created today 2023-11-25 11:01

**Comment by scottanderson** [comment]
Loading from and exporting to new save file format should work now. Please open a new issue for any problems you experience with the new functionality. Please remember to include your save file when reporting new issues, thanks!
