### ISSUE TITLE
Failed to load: Error: NameProperty data type for 'SplineTrackIds' is not implemented

### ISSUE THREAD

**Issue by orffen** [scottanderson/railroad.studio#64]
**Describe the bug**
```javascript
Error: NameProperty data type for 'SplineTrackIds' is not implemented
    at Oi (https://railroad.studio/studio.js:1:246938)
    at Bi (https://railroad.studio/studio.js:1:239411)
    at https://railroad.studio/studio.js:1:249179
    at https://railroad.studio/studio.js:1:249382
    at https://railroad.studio/studio.js:1:248000
```

**To Reproduce**
Try to load a save game from version 0.6.0.0.3

**Expected behavior**
Save game loads

**Comment by scottanderson** [comment]
Thank you for the report @orffen. I have added support for the `NameProperty` data type, as well as two others that were missing. I'm going to resolve this issue and use #63 to track other issues related to loading saves with the new update.

Please feel free to reopen this issue or create a new one if you see another `data type is not implemented` error. Please include a save file with your report to make it easier to reproduce the issue.
