### ISSUE TITLE
Failed to load: Error: NameProperty data type for 'IndustryNameArray' is not implemented

### ISSUE THREAD

**Issue by OrionsStarr** [scottanderson/railroad.studio#65]
**Describe the bug**
Opened a brand new save into Railroad Studio. Nothing previously built in the world.

**To Reproduce**
1. Create new save game in RRO (No tracks built)
2. Open save in Railroad Studio
3. Error given

**Expected behavior**
Save opens

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX

**Comment by scottanderson** [comment]
Thank you for the report @OrionsStarr. I have added support for the NameProperty data type, as well as two others that were missing. I'm going to resolve this issue and use https://github.com/scottanderson/railroad.studio/issues/63 to track other issues related to loading saves with the new update.

Please feel free to reopen this issue or create a new one if you see another data type is not implemented error. Please include a save file with your report to make it easier to reproduce the issue.
