### ISSUE TITLE
Lima Boiler pressure not correct.

### ISSUE THREAD

**Issue by Bullzdozer** [scottanderson/railroad.studio#81]
The lima boiler pressure is incorect.

it has 200psi not 160 as studio states and it seem to not like the lima boiler pressure even if i adjust it to below 160psi so the pressure just keeps showing marked with pinkish color.

the slider was at 115% when i loaded the save aka 200psi

![image](https://github.com/scottanderson/railroad.studio/assets/78733726/f31d68ad-994b-420c-9386-6dbc31cd526b)

not able to download my save guessing because the lima shrows an error on the boiler pressure value?

**Comment by scottanderson** [comment]
@Bullzdozer can you please include the affected sav file?

**Comment by Bullzdozer** [comment]
[.Manual Save.zip](https://github.com/scottanderson/railroad.studio/files/13481738/default.Manual.Save.zip)

here u go.

**Comment by scottanderson** [comment]
Resolved with #87
