### ISSUE TITLE
Uncaught Error: Unrecognized property: WeatherChangeIntervalMax

### ISSUE THREAD

**Issue by knoellix** [scottanderson/railroad.studio#82]
**Describe the bug**

**To Reproduce**
1. Load Save
2. modify anything
3. Click Save / Download 
4. Nothing happen
5. In Console stands:
    Uncaught Error: Unrecognized property: WeatherChangeIntervalMax
    at studio.js:1:235024
    at HTMLButtonElement.<anonymous> (studio.js:1:235308)

**Expected behavior**
Download dialog for new Save 

**Screenshots**
![opera_y6dPay8HSZ](https://github.com/scottanderson/railroad.studio/assets/128321164/6aaf8b8c-1e29-404c-a219-98757ef7831c)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Operea GX
 - Version [e.g. 22] Newest

**Comment by scottanderson** [comment]
@knoellix can you please include the affected sav file?

**Comment by scottanderson** [comment]
Fixed in #86
