### ISSUE TITLE
Tracks not displaying in UI.

### ISSUE THREAD

**Issue by rfatz9191** [scottanderson/railroad.studio#83]
**Describe the bug**
When loading save (save started in Patch 0.6.0.0.3, v2), no tracks display in UI. Other entities are displayed (rolling stock, industries, telegraph, etc)

**To Reproduce**
1. Go to railroad.studio
2. upload savegame
3. save loads, but no rails present.

**Expected behavior**
rails and attributes should display as expected.

**Screenshots**
example around sawmill:
![image](https://github.com/scottanderson/railroad.studio/assets/151971993/7e35556a-df4e-4071-ae96-1c96954a4152)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Chrome (ersion 119.0.6045.160)  and Edge (Version 119.0.2151.72 )

**Additional context**
saves created on older version appear to open with rails showing.

**Comment by scottanderson** [comment]
@rfatz9191 can you please include the affected sav file?

**Comment by rfatz9191** [comment]
[BOYZ.zip](https://github.com/scottanderson/railroad.studio/files/13468880/BOYZ.zip)
@scottanderson Please see attached.

**Comment by scottanderson** [comment]
Fixed in #86
