### ISSUE TITLE
Unsupproted industry enginehouse_princess causing track to not load

### ISSUE THREAD

**Issue by ColdFerrin** [scottanderson/railroad.studio#88]
**Attach the save file**
[Lake.zip](https://github.com/scottanderson/railroad.studio/files/13538326/Lake.zip)

**Describe the bug**
Uncaught (in promise) Error: Unsupproted industry enginehouse_princess when loading save on lake map. This causes the track to not load.

Shown when loading map on lake

**To Reproduce**
Select Map in main screen.
Look in console

**Expected behavior**
Track should load,

 - OS: Windows 11
 - Browser Firefox
 - Version 120.0.1

**Comment by ColdFerrin** [comment]
Further testing shows this is present on pine valley as well. 
[test.zip](https://github.com/scottanderson/railroad.studio/files/13538332/test.zip)

**Comment by Pyrotrainthing** [comment]
I am confirming this has also happened to me on a Lake Valley map too. Attached is my affected Lake Valley save.
[LakeValley.zip](https://github.com/scottanderson/railroad.studio/files/13539498/LakeValley.zip)

**Comment by scottanderson** [comment]
Fixed in #90
