### ISSUE TITLE
missing Loco and a missing Engine House

### ISSUE THREAD

**Issue by lazer1982** [scottanderson/railroad.studio#97]
[Dark Skyes RR.zip](https://github.com/scottanderson/railroad.studio/files/13789969/Dark.Skyes.RR.zip)
![Engian house](https://github.com/scottanderson/railroad.studio/assets/99909749/b262c670-912c-4556-9638-ef6d05eba4ec)
shows up as a blank. 
![Loco](https://github.com/scottanderson/railroad.studio/assets/99909749/495d520d-8bb6-40a9-8c13-a0db705873a5)
![2-4-2t](https://github.com/scottanderson/railroad.studio/assets/99909749/a52874a6-3d63-493a-bbe0-4a98bf01b0fd) 
just totaly missing for railroad.studio

**Comment by nomisthenoob** [comment]
yes ... a lot of the new stuff that came out is missing...new industries engine etc... hoping it will all get updated ...it is the holiday season so it might be awhile

**Comment by scottanderson** [comment]
The attached save should work following #99 and #101.
